apiVersion: v1
# Type secret for storing data in base64 encoded
kind: Secret 
metadata:
  # name of secret
  name: mongodb-secret 
# default - for arbitrary key-value pairs
type: Opaque 
data:
  # encoded username
  mongo-root-username: dXNlcm5hbWU= 
  # encoded password
  mongo-root-password: cGFzc3dvcmQ= 
