apiVersion: apps/v1
kind: Deployment # kind deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1 # no of replicas 
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express # label name
    spec:
      containers:
      - name: mongo-express
        image: mongo-express # base image / container name
        resources: # resource limitation
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081 # port which container is listening to
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME # ENV required to login
          valueFrom: # takingfrom other file
            secretKeyRef: # its type is secret 
              name: mongodb-secret # file metaname name
              key: mongo-root-username # which key
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
             name: mongodb-secret
             key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: 
            configMapKeyRef: # its type is configMap
              name: mongodb-configmap # file metaname name
              key: database_url # which key
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer # Saying the type is external aka loadbalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081 # is where the container is listening 
    nodePort: 30000 # is the port were the external IP address will be open, must be range in (30,000 - 32,767)